default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  encoding: utf8mb4
  pool: 6

development: &development
  <<: *default
  database: firstapp_development
  host:     <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port:     <%= ENV['DATABASE_PORT'] || '3306' %>
  username: <%= ENV['DATABASE_USER'] || 'root' %>
  password: <%= ENV['DATABASE_PASS'] || '' %>


test: &test
  <<: *development
  database: firstapp_test

production:
  <<: *default
  database: firstapp_production
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] || '3306' %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
