version: '3.7'

services:
  db:
    image: mysql:5.7
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --init-connect='SET NAMES utf8mb4'
        --sql-mode=''
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=firstapp_development
      - MYSQL_USER=root
    ports:
      - "7306:3306"
    volumes:
      - db-data:/var/lib/mysql
    container_name: firstqpp_db
    init: true
  redis:
    image: 'redis:5.0.5'
    container_name: firstapp_redis
    init: true
  backend:
    container_name: firstapp_rails
    build: ./backend
    volumes:
      - ./backend:/app
      - backend-bundle:/usr/local/bundle
      - web-cache:/app/tmp
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_HOST: db
    command: bash -c "rm -f /app/tmp/pids/server.pid & bundle exec rails db:migrate RAILS_ENV=development & bundle exec rails s -p 3000 -b 0.0.0.0"
    links:
      - db
      - redis
    init: true
    stdin_open: true
    depends_on:
      - db
  frontend:
    container_name: firstapp_nuxt
    build: ./frontend
    ports:
      - "7080:8080"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
volumes:
  db-data:
    driver: local
  web-cache:
  backend-bundle:
  frontend-node-modules:
