version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=firstapp_development
      - MYSQL_USER=root
    ports:
      - "7306:3306"
    volumes:
      - ./backend/db:/var/lib/mysql
    container_name: firstqpp_db
    init: true
  backend:
    container_name: rails
    build: ./backend
    volumes:
      - ./backend:/app
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "7000:3000"
    links:
      - db
    init: true
    stdin_open: true
    depends_on:
      - db
  frontend:
    container_name: nuxt
    build: ./frontend
    ports:
      - "7080:8080"
    volumes:
      - ./frontend:/app
