version: 2
jobs:
  build:
    working_directory: ~/FirstApp
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          DABASE_HOST: 127.0.0.1
          REDIS_HOST: 127.0.0.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        command:
          mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --init-connect='SET NAMES utf8mb4' --sql-mode=''
      - image: circleci/redis:5.0.4

    steps:
      - run:
          name: Install Bundler
          command: gem install bundler -v 1.17.3

      - checkout

      - restore_cache:
          keys:
            - rails-backend-{{ checksum "Gemfile.lock" }}
            - rails-frontend-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: rails-backend-{{ checksum "Gemfile.lock" }}
          paths:
            - backend/bundle

      - save_cache:
          key: rails-frontend-{{ checksum "package.json" }}
          paths:
            - frontend/node_modules

      # Database setup
      - run:
          name: Database Setup
          command: |
            bundle _1.17.3_ exec rake db:create db:migrate --trace
            bundle _1.17.3_ exec rake db:seed --trace

      # rspec
      - run:
          name: RSpec
          command: bundle exec rake spec

      # rubocop
      - run:
          name: rubocop
          command: |
            bundle _1.17.3_ exec rubocop -f html > /tmp/artifacts/rubocop.html
            bundle _1.17.3_ exec rubocop -D -c .rubocop.yml -f simple

      # brakeman
      - run:
          name: brakeman
          command: bundle exec brakeman

      # ESlint
      - run:
          name: ESLint
          command: npx eslint -o /tmp/artifacts/eslint.html -f node_modules/eslint-html-reporter/reporter.js --ign    ore-pattern vendor ./app/frontend/src/javascripts
